#docker network create -d bridge ml4ds_net --subnet 10.50.0.0/20 --attachable 
#docker build --tag phppython .
#docker-compose up -d
version: "3.2"

networks:
  web-net:
    name: ml4ds_net
    external: true

services:
  web:
    user: "${MYUID}"
    #image: phppython
    build: 
        context: .
        dockerfile: Dockerfile
        args:
            - MYUID=${MYUID}
            - GID=${GID}

    container_name: ITMTWeb
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - NUMBA_CACHE_DIR=/tmp
      - TRANSFORMERS_CACHE=/tmp
      - MPLCONFIGDIR=/tmp


    ports:
      - "4080:80"
    networks:
      - web-net       
    volumes:
        - ./app:/var/www/html  
        - ./auth:/auth
        - /export/data_ml4ds/ITMTWeb/:/data/
        - /export/usuarios_ml4ds/lbartolome/Repos/:/export/usuarios_ml4ds/lbartolome/Repos/:rw

volumes:
  app:


